### ISSUE TITLE
Request for Access to Collaboration Tools for JMCL Granite State Police Project

### ISSUE THREAD

**Issue by aizumo7** [BU-Spark/bu-spark#69]
### Project Name

JMCL Granite State Police Project

### Team Members + Emails + Github Username

Ayu Izumo, aizumo77@gmail.com, aizumo7

### Select Tools Needed

- [ ] Google Drive
- [X] GitHub
- [ ] Notion Board
- [ ] Slack
- [ ] Other (specify below)

**Comment by langdon** [comment]
Done.
