### ISSUE TITLE
Request for Spark! Tech Resources for [CISS Immigration Raids]

### ISSUE THREAD

**Issue by PalmPalm7** [BU-Spark/bu-spark#80]
### Project Name

CISS Immigration Raids

### Project Type

Data Science / Machine Learning

### Team Members + Emails

"Xie, Handi" <hxie13@bu.edu>,
"Zhang, Yuhao" <yuhao24@bu.edu>,
"Pierre-Louis, Farrah" <farrahpl@bu.edu>,
"Daylor, Kaya" <kdaylor@bu.edu>,
"Erozer, Can" <caner@bu.edu>,

### Detailed List of Resources Needed

Access to OpenAI API.
We plan to test our prototype with GPT-4o-turbo.

### Description of Resource Usage

It's only for experimental usage, not for production-level usage.

### Course Deadlines (if applicable)

The sooner the better, we have already pivoted a few times.

**Comment by funkyvoong** [comment]
@PalmPalm7 I added the entire team using the emails you provided, please accept the invite.

**Comment by PalmPalm7** [comment]
> @PalmPalm7 I added the entire team using the emails you provided, please accept the invite.

Thank you Michelle!
