### ISSUE TITLE
Request for Spark! Tech Resources for Racist deeds

### ISSUE THREAD

**Issue by jianyingx12** [BU-Spark/bu-spark#83]
### Project Name

Racist Deeds project

### Project Type

Data Science / Machine Learning

### Team Members + Emails

Jianying Liu Jianying@bu.edu
Jacob Stein jmstein@bu.edu
Nathaniel Quisel njquisel@bu.edu

### Detailed List of Resources Needed

OpenAi Api key

**Comment by funkyvoong** [comment]
@jianyingx12  I added the entire team using the emails you provided, please accept the invite.
