### ISSUE TITLE
Request for Spark! Tech Resources for BPS Policy Chat Bot/Wheelock

### ISSUE THREAD

**Issue by akshatgurbuxani** [BU-Spark/bu-spark#84]
### Project Name

BPS Policy Chat Bot/Wheelock

### Project Type

Data Science / Machine Learning

### Team Members + Emails

Akshat Gurbuxani <imaksht@gmail.com>
Abhaya Shukla <abhaya13@bu.edu>
Mounika Chowdary Akuraju <mounika5@bu.edu>
Duoduo Xu <tedduoduo@gmail.com>

### Detailed List of Resources Needed

I need OpenAI API key for the following models.

1. API key to communicate with the 'gpt-4o-mini' model.
2. API key to create embeddings with the 'text-embedding-3-small' model.

The price break-up is shared below.
Link: [OpenAI API Pricing](https://docs.google.com/document/d/1tv-0aexpNT-K_SEGVHINEUqY4-B2kX4ti8KgXZumCmQ/edit?tab=t.0)

**Comment by funkyvoong** [comment]
@akshatgurbuxani  I added the entire team using the emails you provided, please accept the invite. Let me know if there are any issues.
